- hosts: all
  gather_facts: yes
  become: false
  tasks:
    # now deploy react application
    - name: place react app (takes while)
      copy:
        src={{ playbook_dir }}/../frontend/react/ccnavigator/build/
        dest=/var/www/
        mode=0440
        directory_mode=0550
        owner=www-data
        group=www-data
      become: true
