- hosts: all
  gather_facts: yes #retrieves some variables like ansible_hostname, this fails on first provision, but works when we skip it and install some things and try again...a
  become: true
  tasks:
  - name: install curl
    apt:
      name=curl
  - name: add nodejs repository for install node v9
    shell:
      curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
  - name: install node
    apt:
      name=nodejs
  - name: sync application files dir
    synchronize:
      src=../frontend/react/ccnavigator/public
      dest=/var/www/react/
  - name: sync more application files dir
    synchronize:
      src=../frontend/react/ccnavigator/src
      dest=/var/www/react/
  - name: copy react environment config
    copy:
      src={{ playbook_dir }}/../frontend/react/ccnavigator/.env
      dest=/var/www/react/
  - name: copy node app endpoint config
    copy:
      src=config/Config.js
      dest=/var/www/react/src/config/
  - name: npm pacakage files
    copy:
      src={{ playbook_dir }}/../frontend/react/ccnavigator/package.json
      dest=/var/www/react/
  - name: npm pacakage files
    copy:
      src={{ playbook_dir }}/../frontend/react/ccnavigator/package-lock.json
      dest=/var/www/react/
  - name: install npm packages
    shell: npm install
    args:
      chdir: /var/www/react
  - name: make build react app
    shell: npm run build
    args:
      chdir: /var/www/react
